# Pattern to input fastq files, use {sample} to indicate portion of filename
# that corresponds to the sample name (e.g. data/{sample}.fq.gz)
# The pipeline will automatically detect matching files and process each of them
fastq_file_pattern: "data/{sample}.fastq.gz"

# Output directories
# Directory to put intermediate working files (trimmed reads, bam files, etc.)
working_dir: "results/working"
# Directory to store final results (count matrix, summary reports)
results_dir: "results"

ref:
  # The fasta file for the reference sequence (STAR index will be built automatically)
  fasta: "data/my_genome/my_genome.fa"
  # A GTF file with transcripts 
  # The file should contain `exon` entries, each specifying a `gene_id` attribute
  # GTF Files from ENSEMBL work well
  # See http://bioinf.wehi.edu.au/featureCounts/ for more information
  annotation: "data/my_genome/my_genome.gtf"

# UMI related options
umi:
  # Use UMI sequence to deduplicate
  # UMIs must be a fixed length sequence appended to each read name
  # The resulting BAM file will contain only uniquely mapping reads (-q 255)
  # This is a requirement for the duplicate marking code (nudup)
  mark_umi_duplicates: No

params:
  # FastQC parameters, see http://www.bioinformatics.babraham.ac.uk/projects/fastqc/
  fastqc:
    extra: ""
  # STAR parameters, see https://github.com/alexdobin/STAR
  star:
    # optional star parameters
    extra: ""
    # Command to unzip gzip files to stdout (zcat, gzcat, etc.)
    zcat_command: "zcat"
  # Trimmomatic parameters, see http://www.usadellab.org/cms/?page=trimmomatic
  trimmomatic:
    # list of trimmers (see manual)
    trimmers:
      - "ILLUMINACLIP:AdaptersTrim.fasta:1:30:7"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:20"
    # optional parameters
    extra: ""
  # NuGEN nudup parameters, see https://github.com/nugentechnologies/nudup
  nudup:
    umi_length: 8
    umi_start: 8
    tmp_dir: "/tmp"
    # optional parameters
    extra: ""
  # featureCounts paramters, see http://bioinf.wehi.edu.au/featureCounts/
  featurecounts:
    feature_type: "exon"
    attribute_type: "gene_id"
    extra: "-Q 50"
